In [14]:
from numpy import *
import numpy as np

In [7]:
x = arange(10)
y = zeros(len(x))

print(y)

for i in range(1,len(x)):
    y[i] = x[i] - x[i-1]

print(x)
print(y)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[0 1 2 3 4 5 6 7 8 9]
[ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [12]:
x = arange(10)
y = zeros(x.shape)

y[1:] = x[1:] - x[:-1]

print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [15]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x[0:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
x[0:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
x[2:3]

array([2])

In [20]:
x[2:4]

array([2, 3])

In [21]:
x[0:3]

array([0, 1, 2])

In [22]:
x[1:3]

array([1, 2])

In [23]:
x[1:1]

array([], dtype=int64)

In [24]:
x[1:2]

array([1])

In [25]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
x[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
x[1:] - x[:-1]

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [32]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
less(5, x)

array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [36]:
argmax(less(5, x))

6

In [18]:
f = np.array([1, 2, 4, 7, 11, 16], dtype=np.float)
np.gradient(f)

array([ 1. ,  1.5,  2.5,  3.5,  4.5,  5. ])

In [19]:
f = np.array([1, 3, 4, 7, 11, 16], dtype=np.float)
np.gradient(f)

array([ 2. ,  1.5,  2. ,  3.5,  4.5,  5. ])

In [20]:
f = 2x + 1
np.fradient(f)

SyntaxError: invalid syntax (<ipython-input-20-dd5695b7b3ec>, line 1)